import type { Metadata } from "next";
import "./globals.css";


const montserrat  = {
  subsets: ['latin'],
  weight: ['400' , '800']
}

export const metadata: Metadata = {
  title: "Prisma Mongoose",
  description: "Generated by crud",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        ></link>
        <link
          href="https://cdn.jsdelivr.net/npm/daisyui@5"
          rel="stylesheet"
          type="text/css"
        />
      </head>
      <body>
        {children}
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
      </body>
    </html>
  );
}
