import type { Metadata } from "next";
import "./globals.css";
import { Montserrat} from "next/font/google";

const montserrat  = Montserrat({
  subsets: ['latin'],
  weight: ['400' , '500' , '600' , '700' , '800' , '900']
})   

export const metadata: Metadata = {
  title: "Prisma Mongoose",
  description: "Generated by crud",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        ></link>
        <link
          href="https://cdn.jsdelivr.net/npm/daisyui@5"
          rel="stylesheet"
          type="text/css"
        />
      </head>
      <body  className={montserrat.className}>
        {children}
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
      </body>
    </html>
  );
}
